[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "ChNvubQTeaSLeNwu2mQhEAtFMKEtJ1S99mMoCnqipeTg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 30000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
